include:
  - project: 'aut/ut-dev/infrastructure'
    ref: main
    file: 'templates/ci/docker/docker.yml'

build-scheduler:
  extends: .build
  variables:
    DOCKERFILE_PATH: ./Dockerfile
    DOCKER_CONTEXT: .

deploy-dev-internal:
  extends: .deploy-dev-internal

deploy-prod-internal:
  extends: .deploy-prod-internal
  variables:
    RTK_SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
    RTK_DO_TRANSFER: 'this is just here to check if it is defined or not'
