include:
  - project: 'aut/ut-dev/infrastructure'
    ref: main
    file: 'templates/ci/docker/docker.yml'

build-scheduler:
  extends: .build

deploy-dev-internal:
  extends: .deploy-dev-internal
  variables:
    REPLICAS: 1
    RTK_SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
    RTK_NFS_HOST: $RTK_NFS_HOST
    RTK_NFS_PATH: $RTK_NFS_PATH
    RTK_SFTP_HOST: $RTK_SFTP_HOST
    RTK_SFTP_PATH: $RTK_SFTP_PATH
    RTK_SFTP_USER: $RTK_SFTP_USER

deploy-prod-internal:
  extends: .deploy-prod-internal
  variables:
    REPLICAS: 1
    RTK_SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
    RTK_NFS_HOST: $RTK_NFS_HOST
    RTK_NFS_PATH: $RTK_NFS_PATH
    RTK_SFTP_HOST: $RTK_SFTP_HOST
    RTK_SFTP_PATH: $RTK_SFTP_PATH
    RTK_SFTP_USER: $RTK_SFTP_USER
