version: "3.9"

services:
  scheduler:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    networks:
      - proxy
    environment:
      - RTK_SSH_PRIVATE_KEY=$RTK_SSH_PRIVATE_KEY
      - RTK_NFS_HOST=$RTK_NFS_HOST
      - RTK_NFS_PATH=$RTK_NFS_PATH
      - RTK_SFTP_HOST=$RTK_SFTP_HOST
      - RTK_SFTP_PATH=$RTK_SFTP_PATH
      - RTK_SFTP_USER=$RTK_SFTP_USER
    deploy:
      replicas: $REPLICAS
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      rollback_config:
        parallelism: 1
        delay: 15s
        order: $ORDER
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        order: $ORDER

networks:
  proxy:
    external: true
